version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rails_hello
permissions:
   - object: /var/www/
     pattern: "**"
     owner: ec2-user
     mode: 775
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/clean
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
