#!/bin/bash

yum -y install git make gcc-c++ patch libyaml-devel libffi-devel libicu-devel zlib-devel readline-devel libxml2-devel libxslt-devel ImageMagick ImageMagick-devel openssl-devel libcurl libcurl-devel curl

curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
yum -y install nodejs

yum install sqlite-devel

git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
source .bash_profile

git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
rbenv rehash

rbenv install 2.6.3
rbenv rehash
rbenv global 2.6.3

gem install bundle
gem install rails -v 5.2.1
gem install sqlite3 -v 1.3.13

